CREATE USER master_trainer IDENTIFIED BY pokemon;

-- DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS
-- DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS
--
-- GRANT dba TO master_trainer;
--
-- DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS
-- DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS DO NOT DO THIS

GRANT CONNECT TO master_trainer;
GRANT CREATE ANY TABLE TO master_trainer;
GRANT UPDATE ANY TABLE TO master_trainer;
GRANT DELETE ANY TABLE TO master_trainer;
GRANT INSERT ANY TABLE TO master_trainer;
GRANT UNLIMITED TABLESPACE TO master_trainer;
GRANT CREATE ANY TABLE TO  master_trainer;
GRANT DROP ANY TABLE TO master_trainer;
GRANT CREATE ANY TRIGGER TO master_trainer;
GRANT CREATE ANY SEQUENCE TO master_trainer;
GRANT CREATE ANY PROCEDURE TO master_trainer;

